// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A cloned voice just added to naru-audio (mesa task 1418,
 * `POST /api/config/speech/voices`).
 */
export type AddedVoice = { 
/**
 * The voice's id — the name it was added under.
 */
voice: string, 
/**
 * The clip's length in seconds, as the daemon measured it.
 */
duration: number | null, 
/**
 * The text-to-speech models whose voice list now has it. Only a model
 * that clones lists cloned voices, so this is where it can be picked;
 * empty when Naru could not ask.
 */
models: Array<string>, };
