// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentChild } from "./AgentChild";

/**
 * One live Claude Code session as reported by `claude agents --json`.
 * Parsed from that external CLI output and re-served to the web UI verbatim,
 * so field names stay camelCase end to end (serde renames both directions).
 */
export type AgentSession = { 
/**
 * OS process id; absent once the session's process has exited.
 */
pid: number | null, 
/**
 * Short job id (`claude attach <id>`); background sessions only, so this
 * is also the "attachable" marker.
 */
id: string | null, cwd: string, 
/**
 * `background` (started with `--bg`, attachable) or `interactive`
 * (someone's own terminal — listed, but not attachable).
 */
kind: string, 
/**
 * Session start, milliseconds since epoch.
 */
startedAt: number, sessionId: string, name: string | null, 
/**
 * e.g. `busy` | `idle`; absent once the process has exited.
 */
status: string | null, 
/**
 * e.g. `working` | `blocked` | `done` | `failed` | `stopped`.
 */
state: string | null, 
/**
 * What a blocked session is waiting on (e.g. "permission prompt").
 */
waitingFor: string | null, 
/**
 * **mesa-derived, not from the CLI payload** (hence `serde(default)`, so
 * parsing `claude agents --json` still works): how many shell children
 * this session's process currently has. Claude Code runs one
 * `/bin/zsh -c …` child per Bash tool call, so a nonzero count means a
 * Bash call is in flight *right now* — even when `state` says `done`.
 */
liveShells: number, 
/**
 * **mesa-derived, not from the CLI payload.** How many of this session's
 * subagent transcripts were written within `cc::ACTIVE_SECS`. Subagents
 * run in-process (no child process), so their jsonl mtimes are the only
 * available liveness signal.
 */
liveSubagents: number, 
/**
 * **mesa-derived, not from the CLI payload.** The tail of what this
 * session's assistant last said, read live off its transcript and
 * **bounded** by `cc::sanitize_capped` — it is untrusted model-authored
 * text on a 3-second poll, so it is capped and stripped of control
 * characters exactly as a stored preview is. `null` when the transcript
 * is missing or has no assistant prose in its window.
 */
lastResponse: string | null, 
/**
 * **mesa-derived, not from the CLI payload.** The context window this
 * session currently occupies: the newest assistant message's
 * `input + cache_read + cache_creation` tokens. Not a sum across
 * messages and not output tokens — a context window is the size of the
 * newest *request's* input. `null` when no usage is in the window.
 */
contextTokens: number | null, 
/**
 * **mesa-derived, not from the CLI payload.** The model this session is
 * running on now: the one named by the newest assistant message in its
 * transcript window that names any. One model, never a list — a session
 * that switched models mid-conversation reports the current one. `null`
 * when the transcript is missing or names none.
 */
model: string | null, 
/**
 * **mesa-derived, not from the CLI payload.** The work this session holds
 * in flight right now, one card per item (mesa task 1277): every subagent
 * transcript inside `cc::ACTIVE_SECS` and every live shell child. The
 * list is the detailed twin of `live_shells`/`live_subagents`, never a
 * replacement — the counts keep their exact meaning, and a **finished**
 * subagent still inside the freshness window is listed here while
 * counting toward neither.
 *
 * Always present, empty when there is nothing live. Subagents come first,
 * then shells; the page decides the order it renders (`agentChild.ts`).
 */
children: Array<AgentChild>, 
/**
 * **mesa-derived, not from the CLI payload** (mesa task 1484). What the
 * session says it is doing right now, for the Agents panel's headline:
 * the in-progress `activeForm` of its newest `TodoWrite`, else the
 * newest `description` a tool call carried. `null` when neither is in
 * the transcript window — the page then falls back to `last_response`.
 * Bounded by `cc::sanitize_capped`.
 */
activity: string | null, 
/**
 * **mesa-derived** (task 1484): the id of the task whose `owner` is this
 * session's id, when one claimed its work that way. `null` is the common
 * case — the page then shows the workspace instead.
 */
taskId: number | null, 
/**
 * The `task_id` task's derived name, so the card can label the link.
 */
taskName: string | null, };
