// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentChildKind } from "./AgentChildKind";
import type { AgentChildState } from "./AgentChildState";

/**
 * One piece of work hanging off a live session (mesa task 1277) — a subagent
 * or a shell — as the Agents panel's child cards show it.
 *
 * Every field but `kind`/`name`/`state` is optional because each is a
 * best-effort read of something outside mesa (a transcript tail, a `ps`
 * row): an unreadable file yields a child with what is known rather than no
 * child at all.
 */
export type AgentChild = { 
/**
 * This child's own identity, where it has one: a subagent's transcript
 * file stem (`agent-<name>-<hex>`), which is what
 * `GET /api/cc/sessions/{id}/subagents/{agent_id}/chat` takes to open it
 * in a read-only pane (mesa task 1278). A bounded pointer, so it belongs
 * on the record beside the rest of the card.
 *
 * `None` for a shell, and not an omission: a `ps` row carries nothing
 * transcript-derived, so a Bash call in flight has no identity beyond
 * the command line already in `name`.
 */
id: string | null, kind: AgentChildKind, 
/**
 * A subagent's `agentType` (from the transcript's `.meta.json` sidecar,
 * falling back to the file stem), or a shell's command line. Bounded by
 * `cc::sanitize_capped` like every other string mesa lifts out of an
 * external file — untrusted text on a poll.
 */
name: string, 
/**
 * The last thing a subagent did: its newest assistant prose, else the
 * tool that message called. `None` for a shell — a Bash call in flight
 * has produced no output yet — and for a subagent that has said nothing.
 */
detail: string | null, 
/**
 * When this child started, as mesa's own stored timestamp text
 * (`YYYY-MM-DD HH:MM:SS`, UTC) so the page parses it exactly as it parses
 * a db timestamp. `None` when neither the transcript nor `ps` says.
 */
startedAt: string | null, 
/**
 * A subagent's occupied context window, the same
 * `input + cache_read + cache_creation` figure a session's own
 * `context_tokens` is. Always `None` for a shell.
 */
contextTokens: number | null, 
/**
 * The model a subagent is running on now, the same "newest message that
 * names one" figure a session's own `model` is. Always `None` for a
 * shell: a `ps` row is all there is of one, and it names no model.
 */
model: string | null, 
/**
 * What this child is for, in plain English (mesa task 1484). A
 * subagent: the `description` in its `.meta.json` sidecar. A shell: the
 * `description` on the parent's pending `Bash` call it was paired with
 * (`agents::pair_shells`). `None` when unknown.
 */
description: string | null, 
/**
 * A shell's real command, from the paired pending `Bash` call rather than
 * the `zsh -c 'source …'` wrapper `ps` shows. `None` for a subagent and
 * for a shell no pending call could be paired with.
 */
command: string | null, state: AgentChildState, };
