// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CcLiveSubagent } from "./CcLiveSubagent";
import type { CcRepeat } from "./CcRepeat";
import type { CcTokens } from "./CcTokens";

/**
 * One currently-running Claude Code session — a session whose newest transcript
 * event lands inside the live window. The `spark` is a per-minute token series
 * (oldest→newest, one entry per bucket of [`CcLive::bucket_seconds`]) so the UI
 * can draw a heartbeat of recent activity.
 */
export type CcLiveSession = { session_id: string, 
/**
 * Short name (last path component of `cwd`).
 */
project: string | null, cwd: string | null, git_branch: string | null, models: Array<string>, 
/**
 * First/last in-window event timestamps (ISO-8601 UTC).
 */
started: string, last_activity: string, 
/**
 * Seconds since the last event (`now - last_event`); small ⇒ actively working.
 */
idle_seconds: number, 
/**
 * `active` (idle within [`CcLive::active_seconds`]) or `idle`.
 */
status: string, 
/**
 * Assistant turns inside the window.
 */
messages: number, tokens: CcTokens, total_tokens: number, est_cost_usd: number, 
/**
 * True if any in-window event came from a subagent (`isSidechain`).
 */
used_subagent: boolean, 
/**
 * Subagents currently running under this session (active within
 * [`CcLive::active_seconds`]), most-recently-active first. Rendered as
 * concise lines under the session card.
 */
subagents: Array<CcLiveSubagent>, 
/**
 * Per-minute total-token buckets over the window, oldest→newest.
 */
spark: Array<number>, 
/**
 * The trailing run of identical trivial `Bash` calls this session is
 * currently in, or `null` when its newest tool call was anything else.
 * The cost guard's `repeat` rule reads it (`docs/cost-guard.md`).
 */
repeat: CcRepeat | null, 
/**
 * The newest main-thread (non-sidechain) assistant turn's input side —
 * `input + cache read + cache creation` tokens, the measure
 * `SessionPulse.context_tokens` uses — or `null` when none was seen in the
 * window. The cost guard's `context` rule reads it (`docs/cost-guard.md`).
 */
context_tokens: number | null, };
