// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A point where an agent definition's `model:` or `effort:` frontmatter key
 * changed between two library versions (the first version is a marker with
 * null `from_*`).
 */
export type CcModelChange = { agent: string, 
/**
 * The version's stored `created_at` (`YYYY-MM-DD HH:MM:SS`, UTC).
 */
at: string, from_model: string | null, to_model: string | null, from_effort: string | null, to_effort: string | null, };
