// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One row of the model scorecard: every subagent run of one agent on one
 * model (`mesa cc scorecard`, mesa task 1514). Reasoning effort is not in any
 * transcript, so it is deliberately not a column here — it rides only on
 * [`CcModelChange`].
 */
export type CcScorecardRow = { agent: string, model: string, 
/**
 * Runs in this group — the sample size every mean below rests on.
 */
runs: number, total_cost: number, cost_per_run: number, turns_per_run: number, tokens_per_run: number, wall_secs_per_run: number, wall_secs_median: number, 
/**
 * Start of the earliest / latest run, `YYYY-MM-DD HH:MM:SS` UTC.
 */
first_run: string, last_run: string, 
/**
 * Runs whose session's first prompt names an existing task (mesa task
 * 1534) — the sample size of the two counts below. Unlinked runs are in
 * `runs` but not here.
 */
task_runs: number, 
/**
 * Of `task_runs`, those whose task is `done` **now**.
 */
task_done: number, 
/**
 * Of `task_runs`, those whose task was moved `in_progress` back to
 * `todo`/`backlog` at or after the run's session started.
 */
task_requeued: number, };
