// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CcModelChange } from "./CcModelChange";
import type { CcScorecardRow } from "./CcScorecardRow";

/**
 * `mesa cc scorecard` / `GET /api/cc/scorecard`.
 */
export type CcScorecard = { rows: Array<CcScorecardRow>, model_changes: Array<CcModelChange>, 
/**
 * The bounds as the caller gave them, echoed; null when absent.
 */
since: string | null, until: string | null, };
