// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CcTokens } from "./CcTokens";

/**
 * One session row for the sessions table.
 */
export type CcSessionRow = { session_id: string, 
/**
 * First/last event timestamps (ISO-8601 UTC, as recorded by Claude Code).
 */
start: string, end: string, duration_minutes: number, models: Array<string>, messages: number, tokens: CcTokens, total_tokens: number, est_cost_usd: number, 
/**
 * Tool calls made in the window (main thread + subagents).
 */
tool_calls: number, 
/**
 * Subagent runs recorded under this session (not window-filtered — runs
 * have no timestamp of their own).
 */
agent_runs: number, cwd: string | null, project: string | null, git_branch: string | null, entrypoint: string | null, 
/**
 * True if any of the session's events came from a subagent (`isSidechain`).
 * Subagent transcripts reuse the parent's `sessionId`, so this is "the
 * session used a subagent", not "the session *is* a sidechain".
 */
used_subagent: boolean, 
/**
 * The live conversation this cc session drove, if any (mesa task 1448) —
 * derived on every read from the exact "Drive naru live session <id>"
 * line the session's driver was spawned with
 * (`Store::cc_live_session_links`), never stored and never guessed by
 * timing. `None` for every other session.
 */
live_session_id: number | null, 
/**
 * Whiteboards pushed during that live session (`live_boards`), present
 * iff `live_session_id` is. Derived, never stored.
 */
live_board_count: number | null, };
