// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CcSessionBucket } from "./CcSessionBucket";
import type { CcSessionModelStat } from "./CcSessionModelStat";
import type { CcSessionSkillStat } from "./CcSessionSkillStat";
import type { CcSessionThreadStat } from "./CcSessionThreadStat";
import type { CcSessionToolStat } from "./CcSessionToolStat";
import type { CcTokens } from "./CcTokens";

/**
 * One session's aggregate detail — `GET /api/cc/sessions/{id}` and
 * `mesa cc session <ID>`, the default drill-down from the sessions table.
 *
 * Aggregated server-side over **every** persisted row, deliberately not
 * derived from [`CcSessionGraph`]: that payload caps its tool nodes, and its
 * tool/response nodes repeat their issuing message's usage, so neither an
 * exact per-tool count nor a token-over-time series is recoverable from it.
 */
export type CcSessionDetail = { session_id: string, cwd: string | null, 
/**
 * Short name (last path component of `cwd`), same derivation as
 * [`CcSessionRow`].
 */
project: string | null, git_branch: string | null, entrypoint: string | null, 
/**
 * Session span (ISO-8601 UTC), when known.
 */
start: string | null, end: string | null, duration_minutes: number, used_subagent: boolean, 
/**
 * The live conversation this session drove, if any — see
 * [`CcSessionRow::live_session_id`]. `None` for every other session.
 */
live_session_id: number | null, 
/**
 * Whiteboards pushed during that live session, present iff
 * `live_session_id` is. Derived, never stored.
 */
live_board_count: number | null, 
/**
 * Whole-session rollup: main thread + every subagent.
 */
tokens: CcTokens, total_tokens: number, est_cost_usd: number, messages: number, tool_calls: number, 
/**
 * Subagent runs recorded under this session.
 */
agent_runs: number, 
/**
 * The main thread alone — the half of the rollup that is not subagents.
 */
main: CcSessionThreadStat, 
/**
 * One entry per subagent thread, `total_tokens` desc (`agent_id` asc ties).
 */
agents: Array<CcSessionThreadStat>, models: Array<CcSessionModelStat>, tools: Array<CcSessionToolStat>, skills: Array<CcSessionSkillStat>, 
/**
 * Evenly-sized buckets over the session span; see
 * [`crate::core::cc::ACTIVITY_BUCKETS`].
 */
activity: Array<CcSessionBucket>, };
