// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The speech settings as the Settings page sees them (`core::config`,
 * `docs/config.md`, mesa task 822) — a fourth view of `~/.mesa/config.json`,
 * with the same null-means-fallback rule as [`ConfigWatchers`].
 */
export type ConfigSpeech = { 
/**
 * The configured voice for the inbox's play button, or `null` when the
 * config says nothing — then the synthesiser's own default applies and
 * mesa passes no `-v` at all.
 */
voice: string | null, 
/**
 * Every voice the installed `kokoro-rs` reports (`--list-voices`), so the
 * editor can offer a list. **Empty means mesa could not ask** — a missing
 * or uncooperative binary — never "there are no voices", so an empty list
 * is a reason to accept a typed name, not to refuse one. On naru-audio
 * these are the voices of the configured `model` — or of the one
 * `GET /api/config/speech?model=` named (mesa task 1425).
 */
voices: Array<string>, 
/**
 * The configured text-to-speech model (mesa task 1425), or `null` when the
 * config says nothing — then naru-audio speaks in its own default model.
 * Only the naru-audio engine sends it.
 */
model: string | null, 
/**
 * Every text-to-speech model naru-audio lists (`GET /v1/models`,
 * `x_kind == "tts"`). Always empty on the legacy engine — `kokoro-rs`
 * has one model — and empty on naru-audio when Naru could not ask.
 */
models: Array<string>, };
