// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The listen settings as the Settings page sees them (`core::config`,
 * `docs/config.md`, mesa task 955) — the input-side mirror of
 * [`ConfigSpeech`]: the model the external `auris` speech-to-text binary is
 * run with, plus the models the installed binary offers.
 */
export type ConfigListen = { 
/**
 * The configured model `live transcribe` runs `auris` with, or `null`
 * when the config says nothing — then no `-m` is passed at all and
 * `auris` picks its own default.
 */
model: string | null, 
/**
 * Every model the installed `auris` reports (`--list-models`), so the
 * editor can offer a list. **Empty means mesa could not ask** — a missing
 * or uncooperative binary — never "there are no models", so an empty
 * list is a reason to accept a typed name, not to refuse one.
 */
models: Array<string>, 
/**
 * What the **page** listens with (mesa task 1388), verbatim: `"server"`,
 * `"browser"`, or `null` when the config says nothing.
 */
engine: string | null, 
/**
 * The built-in page engine (`"server"`).
 */
engine_default: string, 
/**
 * The speech vocabulary (naru task 1754), verbatim — naru-audio's
 * `hotwords` text — or `null` when none is configured.
 */
vocabulary: string | null, 
/**
 * The speech-to-text models whose backend uses the vocabulary
 * (`x_hotwords` on the daemon's model list). Empty on the legacy engine
 * and when the daemon could not be asked.
 */
hotword_models: Array<string>, 
/**
 * The daemon's default speech-to-text model, so the page can judge the
 * vocabulary for a model nobody configured; `null` when unknown.
 */
default_model: string | null, };
