// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ServeBoolSetting } from "./ServeBoolSetting";
import type { ServeHostsSetting } from "./ServeHostsSetting";
import type { ServeNumberSetting } from "./ServeNumberSetting";

/**
 * The `serve` section as the Settings page sees it (`GET
 * /api/config/serve`, mesa task 1621): every `naru serve` startup flag as a
 * config key. `port`, `lan` and `allow_host` are read once at start, so a
 * change needs a restart (`restart_required`); the five watcher switches are
 * read on every tick.
 */
export type ConfigServe = { port: ServeNumberSetting, lan: ServeBoolSetting, allow_host: ServeHostsSetting, watch_todo: ServeBoolSetting, watch_inbox: ServeBoolSetting, watch_cost: ServeBoolSetting, watch_retro: ServeBoolSetting, watch_workflows: ServeBoolSetting, 
/**
 * True when the port, LAN switch or allowed hosts the config would give a
 * fresh start differ from what this process is running with.
 */
restart_required: boolean, };
