// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The rates a request pays when its prompt (input + cache read + cache
 * creation tokens) is strictly over `above_tokens`; every token kind of that
 * request, output included, is priced at these. USD per **1M tokens**.
 */
export type ContextTier = { above_tokens: number, input: number, output: number, cache_read: number, cache_write: number, };
