// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One git repo discovered under a project's `local_path` (see
 * `core::git::discover_repos`), for the git tab's repo picker.
 */
export type GitRepo = { 
/**
 * Path relative to `local_path`; `"."` is `local_path` itself. This is
 * exactly the value `?repo=` accepts on the git routes.
 */
path: string, 
/**
 * Checked-out branch; short sha when detached; None on an unborn HEAD
 * or when git could not be asked.
 */
branch: string | null, };
