// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LibraryKind } from "./LibraryKind";
import type { LibraryScope } from "./LibraryScope";

/**
 * One library row as it travels between mesa instances.
 *
 * `Deserialize` is written by hand rather than derived (`impl` below)
 * because a bundle exported before mesa task 1139 carries `"kind":
 * "command"`, a word [`LibraryKind`] no longer has: it is read as a prompt
 * with `export_command` on — the same row the migration made of every stored
 * command — so an old export still imports. Nothing else in mesa reads the
 * old word.
 */
export type LibraryBundleItem = { name: string, kind: LibraryKind, scope: LibraryScope, 
/**
 * The project's NAME, not its id — ids are machine-local. Present iff
 * `scope` is `project`, resolved back to an id on import via
 * `Store::find_project_by_name`.
 */
project: string | null, body: string, 
/**
 * The built-in this row forked from, so a fork imports as a fork.
 */
builtin_id: string | null, 
/**
 * [`LibraryItem::export_command`]; absent in a bundle older than mesa
 * task 1139, which reads as `false`.
 */
export_command: boolean, 
/**
 * [`LibraryItem::files`]; absent in a bundle older than mesa task 1604,
 * which reads as none.
 *
 * `None` is "this bundle says nothing about the siblings" (an old
 * bundle, or a skill with none): import leaves a local skill's siblings
 * alone and the preview does not compare them. A carried map is
 * authoritative.
 */
files?: Record<string, string>, };
