// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LibraryKind } from "./LibraryKind";
import type { LibraryScope } from "./LibraryScope";

/**
 * One library record — an agent definition, a skill, a hook script, a
 * prompt, or a CLAUDE.md, stored in mesa and synced against a file on disk
 * (a prompt only when it `export_command`s).
 *
 * `id` is `null` for an unshadowed built-in (`core::library::BUILTINS`) —
 * there is no db row yet, `builtin` is `true`, and `builtin_id` names which
 * built-in it is. Editing a built-in forks it: a db row appears carrying
 * `builtin_id`, `builtin` becomes `false`, and `id` becomes real.
 */
export type LibraryItem = { id: number | null, 
/**
 * `^[A-Za-z0-9][A-Za-z0-9._-]*$`, no `/`, no `..` — half of a filename.
 */
name: string, kind: LibraryKind, scope: LibraryScope, 
/**
 * Required iff `scope` is `project`, and must be null iff `scope` is
 * `user` — the same pairing rule `TaskPatch`'s neighbours enforce.
 */
project_id: number | null, 
/**
 * The file's contents. May be empty.
 */
body: string, 
/**
 * The built-in this row forked from, or null for a purely user-authored
 * row. Unique when set — a built-in forks at most once.
 */
builtin_id: string | null, 
/**
 * Derived, never stored: true iff this row has no db id (an unshadowed
 * built-in reported in its place).
 */
builtin: boolean, 
/**
 * `prompt` only (mesa task 1139): whether this prompt is *also* written
 * to `.claude/commands/<name>.md`, so Claude Code offers it as the slash
 * command `/<name>`. The stored body is what is exported, byte for byte
 * — no frontmatter is synthesised and no `{placeholder}` is rewritten,
 * because the sync compares three plain strings and any transform would
 * read as a permanent conflict. Always `false` on every other kind and
 * on an unshadowed built-in (a built-in is code and carries no flag).
 */
export_command: boolean, 
/**
 * Derived from `kind`/`scope`/`name`/`export_command` via
 * `core::library::relative_path`; null for a prompt that is not exported
 * as a command, which has no file.
 */
path: string | null, 
/**
 * The last body mesa and the file on disk agreed on — the sync
 * baseline. Null until the first sync.
 */
synced_body: string | null, synced_at: string | null, created_at: string | null, updated_at: string | null, 
/**
 * Derived, never stored (mesa task 1349): true iff this row is a fork
 * whose built-in has changed since the fork last agreed with it — its
 * body differs from the current built-in body, and the stored base (the
 * built-in body at fork time, or at the last `keep`/`take`/`merge`) is
 * unknown or differs too. Always `false` on an unshadowed built-in and
 * on a row with no `builtin_id`.
 */
builtin_updated: boolean, 
/**
 * Derived, never stored: the current built-in body behind a fork, so a
 * client can diff the fork against it; `None` on everything that is not
 * a fork of a built-in that still exists.
 */
builtin_body: string | null, 
/**
 * A `skill`'s sibling files beside `SKILL.md` (mesa task 1604) — path
 * relative to the skill dir to text — so the item carries its whole
 * folder. Empty (and absent on the wire) for every other kind and for a
 * skill that is just `SKILL.md`.
 */
files?: Record<string, string>, };
