// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LibraryDiffLine } from "./LibraryDiffLine";
import type { LibraryKind } from "./LibraryKind";
import type { LibraryScope } from "./LibraryScope";
import type { LibrarySyncStatus } from "./LibrarySyncStatus";

/**
 * One row of a sync scan — one *path*, comparing the mesa side to the disk
 * side. `item_id`/`builtin_id` are both null only for a `disk-new` row (a
 * file with no mesa row at all).
 */
export type LibrarySyncRow = { item_id: number | null, builtin_id: string | null, name: string, kind: LibraryKind, scope: LibraryScope, project_id: number | null, path: string, status: LibrarySyncStatus, mesa_body: string | null, disk_body: string | null, baseline: string | null, 
/**
 * The disk file's mtime, in mesa's own timestamp text (`YYYY-MM-DD
 * HH:MM:SS`, UTC — what SQLite's `datetime('now')` writes for every
 * stored timestamp). `None` when there is no file, or when the platform
 * does not report an mtime for it: a value mesa could not determine is
 * null, never a zero.
 */
disk_mtime: string | null, 
/**
 * When mesa's own side last changed — the newest
 * `library_versions.created_at` for the item when it has any history,
 * else the item's `updated_at`, since `updated_at` also moves on a
 * rename. `None` for an unshadowed built-in (there is no row) and for a
 * `disk-new` row (there is no mesa side).
 */
mesa_updated_at: string | null, 
/**
 * The line-level mesa-vs-disk diff, `Some` only when both sides exist
 * **and** differ — `None` for `in-sync` and for every one-sided status,
 * where the whole body of the one side that exists is the whole story.
 * Deliberately two-way: `baseline` is carried separately, and mesa-vs-disk
 * is what a resolution actually picks between.
 */
diff: Array<LibraryDiffLine> | null, 
/**
 * The row's item is a fork whose built-in changed under it
 * ([`LibraryItem::builtin_updated`], mesa task 1349) — a separate fact
 * from `status`, which compares Naru with the disk and so can read
 * `in-sync` while the built-in has moved on.
 */
builtin_updated: boolean, 
/**
 * A skill's sibling files on each side (mesa task 1604), empty and
 * absent for everything else. They are part of what `status` and `diff`
 * compare: a sibling edit on either side is never `in-sync`.
 */
mesa_files?: Record<string, string>, disk_files?: Record<string, string>, };
