// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LiveBoardKind } from "./LiveBoardKind";

/**
 * One picture the agent put in front of the person during a live conversation
 * (mesa task 1071) — a mockup, a report, a diagram snapshot or a screenshot.
 *
 * A board is deliberately **not** a [`LiveTurn`]: a turn's `text` is spoken
 * and capped at 8 KiB, and [`LiveAction`] is the narrow "what the person is
 * looking at" vocabulary. An HTML mockup is neither small nor speakable, so
 * this is a sibling table, the `LiveSummary` precedent.
 *
 * It is also **ephemeral**, in the sense of *scoped to its conversation*: an
 * ended conversation keeps its rows (the `live_turns` rule — `ended_at` is a
 * stamp, not a delete) but every read of a board closes, the render route
 * included, and nothing reaches a project until `mesa live board keep` copies
 * it into an artifact or an attachment. `session_id` is `ON DELETE CASCADE`
 * for the case that really is a delete.
 */
export type LiveBoard = { id: number, session_id: number, kind: LiveBoardKind, 
/**
 * What to call it in the panel's head row. Optional, bounded, and folded
 * to absent when blank — the [`LiveContext`] rule, for the same reason.
 */
title: string | null, 
/**
 * The whole picture: markdown source, an HTML document, SVG markup, or
 * base64 of an image file's bytes, depending on `kind`. The one unbounded
 * field, which is why `--quiet` drops it and [`LiveBoardSummary`] has
 * none of it.
 */
body: string, 
/**
 * The allowlisted image mime an `image` board's bytes are, taken from the
 * pushed file's extension at push time (`files::image_mime`, the same
 * allowlist `/files/raw` uses). Null for every other kind, whose type the
 * kind itself decides ([`LiveBoardKind::content_type`]). Named for
 * [`Attachment::content_type`] and `artifacts.content_type`, which are
 * this same field on the two other tables that store one.
 *
 * It is stored rather than re-derived because nothing else on the row
 * carries it: `body` is bytes, and `title` is a caption the caller may
 * write anything into, so a render that read the type off the title would
 * change what it serves when the caption changed.
 */
content_type: string | null, 
/**
 * When it was pushed (SQLite `datetime` text, UTC).
 */
created_at: string, 
/**
 * When it was first pinned (naru task 1735); null = not pinned.
 */
pinned_at: string | null, };
