// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LiveBoardSummary } from "./LiveBoardSummary";
import type { LiveOffer } from "./LiveOffer";
import type { LiveSession } from "./LiveSession";
import type { LiveTurn } from "./LiveTurn";

/**
 * The Live page's whole read (`GET /api/live`): the conversation that is
 * running, and the turns after the cursor the page asked from. A **view**,
 * never stored — it is assembled per request out of the one live session and
 * a slice of its turns, the same way [`ProjectAgents`] pairs a folder with
 * the sessions found under it.
 *
 * `session` is null when nothing is live, and then `turns` is empty. That is
 * the ordinary idle state of the page, not an error: the button an idle Live
 * page renders is exactly what fixes it.
 */
export type LiveState = { session: LiveSession | null, turns: Array<LiveTurn>, 
/**
 * The boards pushed in this conversation, oldest first and **bodiless**
 * (mesa task 1071) — the whole history the panel steps through, and its
 * last element is the board that is showing. Bounded by the store's own
 * retention (the newest 20 survive a push), so this poll stays a small
 * response no matter how many pictures a conversation went through, and
 * there is deliberately no second route to fetch them from: a body is
 * fetched once, by the render route, for the one board being looked at.
 */
boards: Array<LiveBoardSummary>, 
/**
 * What the agent's `claude --bg` job is waiting on when `claude agents`
 * reports it `blocked` — its `waitingFor` string, e.g. "permission
 * prompt" — else null (mesa task 1157). **Derived per request, never
 * stored**: looked up by the session's `agent_id` through a short-TTL
 * cache, and null for a session with no agent, a job the CLI does not
 * list, or a `claude` that is missing or failing — none of which is an
 * error.
 */
blocked: string | null, 
/**
 * The driving agent's occupied context window in tokens — the figure
 * `naru live context` prints (mesa task 1478), shown in the panel head.
 * **Derived per request, never stored**, through a short-TTL cache keyed
 * by the agent's job id, so a handoff's successor starts from its own
 * number. Null for a session with no agent, a job `claude agents` does
 * not list, or a transcript that cannot be read.
 */
context_tokens: bigint | null, 
/**
 * An overheard "can help" offer waiting for the person to accept it
 * (naru task 1700) — present only while no session is live and the
 * offer is inside its TTL. **Derived per request** from the server's
 * in-memory state, never stored.
 */
offer: LiveOffer | null, };
