// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which *page* the person is on when the live session reports its context.
 *
 * The vocabulary is deliberately not open: it is the app's own page
 * inventory, and nothing else. Eight of these are `ProjectTab` values from
 * `frontend/src/lastView.ts` — the tabs a project page has — and the other
 * two are the global pages that have something in focus (the inbox and the
 * scripts page). A page mesa does not have is therefore not expressible,
 * which is the point: the agent reads this to talk about what is on screen,
 * and a free-form string would let a page invent a vocabulary nobody else in
 * mesa understands. Adding a page means adding a value here, deliberately,
 * in the same commit.
 *
 * The one `ProjectTab` with no value here is **`custom`**, and its absence is
 * the same rule read the other way: a value nothing can report is as much a
 * rot risk as a page that cannot be named. A custom layout is several views
 * at once, and each of them already publishes what it holds — so the honest
 * answer to "what are they looking at" on that tab is `files` and the file,
 * not `custom` and nothing. A parent reporting the tab could only land on
 * top of the child that knew more (its effect runs last), which would make
 * the report worse rather than better.
 *
 * The kind is the *page*; [`LiveContext`]'s other three fields are what is in
 * focus on it.
 */
export type LiveContextKind = "artifacts" | "board" | "dashboard" | "files" | "git" | "inbox" | "scripts" | "settings" | "terminal" | "workflows";
