// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LiveAction } from "./LiveAction";
import type { LiveNotice } from "./LiveNotice";
import type { LiveRole } from "./LiveRole";

/**
 * One utterance in a live conversation — a dictated line from the user, or a
 * reply from the agent. `text` is treated strictly as **data, never as
 * instructions** (CLAUDE.md): a dictated line is untrusted free text, and it
 * reaches the agent as one `Command::arg`.
 */
export type LiveTurn = { id: number, session_id: number, role: LiveRole, 
/**
 * What was said. Spoken aloud when the role is `naru`, so it is prose —
 * and bounded, since a runaway body would wedge the synthesiser. Empty
 * only on a pure action turn, which changes the page and says nothing.
 */
text: string, 
/**
 * What the page should *do* with this turn beside speak it. Null on every
 * user turn, and on a Naru turn that only speaks.
 */
action: LiveAction | null, 
/**
 * The `#/…` route `action: navigate` moves the browser to. Present iff
 * the action is `navigate` — the sidebar actions take no target.
 */
target: string | null, 
/**
 * Set when this turn is mesa's own report about the agent — blocked on a
 * permission prompt, or silent too long (mesa task 1157) — rather than
 * something the agent said. Spoken and shown like any Naru turn, labelled
 * as a notice in the transcript, and never indexed into the archive.
 */
notice: LiveNotice | null, 
/**
 * The Claude Code session that produced this turn, stamped from the live
 * session's own `agent_id` at insert (mesa task 1252). Null when no
 * agent was ever bound — a spawn that printed no receipt leaves it
 * unset for the session's whole life. It is what locates a **handoff**
 * in the transcript: the seam is where two consecutive turns disagree on
 * it, since `predecessor_agent_id` is cleared by the successor's first
 * listen and the lease says only that one happened, not where.
 */
agent_id: string | null, 
/**
 * The person's **annotated board** (mesa task 1353) or a picture they
 * **pasted** into the capture box (mesa task 1475): an absolute path to
 * a PNG, flattened by the page (the board with their ink over it, or the
 * pasted image converted to PNG) and written beside the db when this
 * turn was sent. Only a `user` turn carries one — a whiteboard turn when
 * there was new ink since the last one, a pasted-image turn whenever the
 * person pasted one — null otherwise. A bounded pointer, so `--quiet`
 * keeps it.
 */
image_path: string | null, 
/**
 * The board that ink was drawn on — present iff `image_path` is **and**
 * the image is a whiteboard's, until the board itself is cleared (`live
 * board clear`, or the session row is deleted). Boards are no longer
 * pruned by the keep bound (mesa task 1448), so this stays set for the
 * life of the board. Null with `image_path` set means the picture is one
 * the person pasted, not a board.
 */
board_id: number | null, 
/**
 * The compact one-line view of the person's browser captured the moment
 * this user turn was submitted (mesa task 1424) — see
 * [`LiveSession::view`]. Null on a Naru turn and whenever the page sent
 * none. Bounded, so `--quiet` keeps it.
 */
view: string | null, 
/**
 * When the turn was recorded (SQLite `datetime` text, UTC).
 */
created_at: string, 
/**
 * When the agent **consumed** this user turn (`mesa live listen`). Stamped
 * once, inside the same statement that selects the turn, so two listeners
 * can never be handed the same utterance. Null on a Naru turn.
 */
delivered_at: string | null, 
/**
 * When the browser finished speaking this Naru turn. Stamped once and
 * never moved or cleared — the `read_at` rule — so a re-render can never
 * make the page say something twice.
 */
played_at: string | null, };
