// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LiveBoardInkEntry } from "./LiveBoardInkEntry";
import type { LiveBoardKind } from "./LiveBoardKind";

/**
 * One entry of a live session's **whole** whiteboard history (`GET
 * /api/live/sessions/{id}/boards`, mesa task 1448) — every board that
 * session ever pushed, oldest first, since retention stopped pruning them
 * (`docs/live.md` "Retention is the history"). Bodiless like
 * [`LiveBoardSummary`]; a caller renders `id` through the ordinary
 * `GET /api/live/boards/{id}/render` route, unchanged, and each of its
 * `ink` entries through `GET /api/live/turns/{turn_id}/ink`.
 */
export type LiveBoardHistoryEntry = { id: number, kind: LiveBoardKind, title: string | null, created_at: string, 
/**
 * The person's annotated snapshots of this board, oldest first — every
 * `live_turns` row that carried one (mesa task 1353).
 */
ink: Array<LiveBoardInkEntry>, };
