// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LiveBoardSummary } from "./LiveBoardSummary";

/**
 * One page of the global whiteboard history (`GET /api/live/boards`, naru
 * task 1735): boards from every session, newest first, plus every pinned
 * board whatever page it falls on.
 */
export type LiveBoardHistoryPage = { boards: Array<LiveBoardSummary>, pinned: Array<LiveBoardSummary>, 
/**
 * Whether boards older than the last one in `boards` exist.
 */
has_more: boolean, };
