// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the ambient engine overheard and judged Naru could help with. The
 * text is capped server-side; `age_ms` lets the page show how stale it is.
 */
export type LiveOffer = { text: string, speaker: string, age_ms: number, };
