// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LiveBoardKind } from "./LiveBoardKind";

/**
 * A board without its body — what rides in [`LiveState`], which the page
 * polls every two seconds. The bodies are megabyte-scale documents and the
 * page only ever renders **one** of them (through the render route, in an
 * `<iframe>` or an `<img>`), so the poll carries the history as pointers and
 * nothing else.
 */
export type LiveBoardSummary = { id: number, session_id: number, kind: LiveBoardKind, title: string | null, created_at: string, 
/**
 * When it was first pinned (naru task 1735); null = not pinned.
 */
pinned_at: string | null, };
