// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LiveContext } from "./LiveContext";
import type { LiveStatus } from "./LiveStatus";
import type { LiveWindow } from "./LiveWindow";

/**
 * One live conversation. **At most one is `live` at a time** (`Store`
 * enforces it): the page has one microphone-shaped text field and one
 * `<audio>` element, so a second concurrent conversation would have nowhere
 * to be heard.
 */
export type LiveSession = { id: number, 
/**
 * The project the conversation is about, or null for an unscoped one. The
 * FK is `ON DELETE SET NULL` (the call the inbox makes): a conversation
 * outlives the project row it mentioned.
 */
project_id: number | null, 
/**
 * The spawn receipt from `agents::spawn_bg` — the Claude session driving
 * this conversation, when the spawn printed one. Null when the session
 * was started with no agent, or when the command printed no receipt.
 */
agent_id: string | null, 
/**
 * Which handoff generation holds the session (mesa task 1150): 1 for a
 * conversation that has never been handed off, bumped by `mesa live
 * handoff` as it rebinds `agent_id` to the successor. A `listen`/`say`
 * presenting a lease the session no longer holds is `conflict`, which is
 * what stops the outgoing agent from driving on; a caller presenting
 * none is never checked.
 */
lease: number, status: LiveStatus, 
/**
 * Where the user's browser currently is (a `#/…` hash route), as last
 * reported by the page. The agent reads it to know what the user is
 * looking at; it is never authority for anything mesa does.
 */
route: string | null, 
/**
 * What is *on* that page — the file, the diagram, the task, the commit —
 * as reported by the page alongside the route, in the same request. The
 * agent reads it to know what is actually on screen rather than asking
 * the person what they are looking at; like `route`, it is never
 * authority for anything mesa does. Null when the page has reported
 * nothing, or has reported that nothing is selected.
 */
context: LiveContext | null, 
/**
 * Where the browser window *itself* is on the screen, as reported by the
 * page in the same request as the route (mesa task 895). Null when no
 * browser has joined the conversation — a session driven from the CLI
 * with `--no-agent` never has one — which is exactly the case
 * `mesa live look` reports as unavailable rather than guessing at.
 */
window: LiveWindow | null, 
/**
 * When the conversation started (SQLite `datetime` text, UTC).
 */
started_at: string, 
/**
 * When the session row was last written — bound to an agent, re-routed,
 * or ended. A turn is its own row and does not move this.
 */
updated_at: string, 
/**
 * When the conversation ended, or null while it is live.
 */
ended_at: string | null, 
/**
 * When the agent last **took** an utterance and started working on it, or
 * null while it is waiting on the person (mesa task 894).
 *
 * The whole of the agent's loop is `listen` → work → `say`, so "waiting"
 * has exactly one shape: a `mesa live listen` sitting inside the wait with
 * nothing to hand out. `Store::next_user_turn` is therefore the one writer
 * — it stamps this when it hands a turn over and clears it on every poll
 * that finds nothing — which is why the span it marks covers *all* of the
 * work, thinking, tool calls and file writes alike, rather than only the
 * moments mesa happens to be talking. A conversation nobody has listened
 * on yet reads as null, so a session started with `--no-agent` never
 * claims someone is working on it.
 */
working_since: string | null, 
/**
 * When the session went to **rest** at a handoff (mesa task 1155), or
 * null. A handoff whose notebook wants a dream pass (`live::dream_wanted`)
 * spawns one beside the successor and stamps this in the same write;
 * the successor's first `listen` waits for the dream agent to finish
 * (or ten minutes) and clears it. The person can still talk — turns
 * queue as ever — but nothing is being worked on, which is what the
 * page shows. Cleared by ending the session.
 */
resting_since: string | null, 
/**
 * Which browser speaks this conversation aloud (mesa task 1267), or null
 * while nobody has claimed it — in which case every client that has had
 * a press may speak, which is what mesa did before this field existed
 * and what an external client that knows nothing of this rule still
 * does.
 *
 * **Derived on every read**, never the raw column: a claim is refreshed
 * by the claiming browser's own route report, and one that has not been
 * refreshed for ten seconds reads as null — a tab that was closed must
 * not leave the conversation mute. So the page compares this with its
 * own client id and needs no clock of its own
 * (`frontend/src/liveSpeaker.ts`).
 */
speaker: string | null, 
/**
 * The latest compact one-line **view** of the person's browser (mesa
 * task 1424) — route, open item and which panels are open, e.g.
 * `p29 claude-config · files · SKILL.md · chat open · agents closed`.
 * Written by a user turn that carries one and by the page's route
 * report; null when no page has said. Data, never instructions.
 */
view: string | null, };
