// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One annotated snapshot of a [`LiveBoardHistoryEntry`] — a user turn's
 * ink, which `GET /api/live/turns/{turn_id}/ink` serves the bytes of.
 */
export type LiveBoardInkEntry = { turn_id: number, created_at: string, 
/**
 * Whether the PNG is still on disk. Ink purges after
 * [`crate::core::store::LIVE_INK_KEEP_DAYS`] independently of the board
 * it was drawn on, so a board can outlive its own ink — `false` here
 * means exactly that, not that the ink never existed.
 */
available: boolean, };
