// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContextTier } from "./ContextTier";

/**
 * One model family's rates, USD per **1M tokens**. All four are explicit —
 * mesa never derives a cache rate from the input rate, because the
 * relationship is a pricing convention, not arithmetic mesa gets to assume.
 */
export type ModelRates = { input: number, output: number, cache_read: number, cache_write: number, 
/**
 * Optional context-size tiers: a request whose prompt is strictly over a
 * tier's `above_tokens` is priced wholly at that tier's rates (the
 * tier with the largest threshold below the prompt wins). Stored
 * ascending by threshold, thresholds unique. Empty = one flat rate, and
 * the key is then omitted so output is byte-identical.
 */
tiers?: Array<ContextTier>, };
