// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GitRepo } from "./GitRepo";

/**
 * `GET /api/projects/{id}/git/repos` response. Empty-state ladder like
 * `ProjectGitView`: path null = no local_path; `repos` empty = dead folder
 * or no repo anywhere under it. Never an error.
 */
export type ProjectGitRepos = { path: string | null, repos: Array<GitRepo>, };
