// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Project = { 
/**
 * ids are SQLite rowids, well within JS safe-integer range, so they are
 * exported as `number` rather than ts-rs's default `bigint` for i64.
 */
id: number, name: string, description: string | null, 
/**
 * Root (first) commit hash of the source repo this project tracks, if any.
 * Stable across clones/worktrees/moved folders, so every checkout of the
 * same source resolves to one project. Set at create time or via update;
 * unique across projects (a commit binds to exactly one project).
 */
root_commit: string | null, 
/**
 * Last-known working folder of this project on this machine (the repo
 * toplevel). Machine-local convenience, not identity (that is
 * `root_commit`): it anchors the Agents surface — which Claude Code
 * sessions belong here, and where new ones start. Auto-learned on
 * `project create` and refreshed by `project resolve`.
 */
local_path: string | null, 
/**
 * Hides the project from unscoped views (project list, unscoped task
 * list/next, sidebar main list) without deleting anything. Flipped via
 * `Store::archive_project` / `unarchive_project`; every query scoped to
 * an explicit project id/name is unaffected.
 */
archived: boolean, 
/**
 * Manual list position (task 666), the project-level twin of
 * `Task::sort_order`: `Store::list_projects` orders by it, so the CLI,
 * the API and the left nav all render one agreed order. Fractional —
 * a drag writes the midpoint between its new neighbours rather than
 * renumbering the list, so one drag is one write. Backfilled from `id`,
 * so an un-dragged install is still in creation order.
 */
sort_order: number, 
/**
 * Parent project (task 668), or `null` at top level. A pure **grouping**
 * relation: the left nav renders the result as a tree, and nothing rolls
 * up — a child keeps its own tasks, diagrams, `root_commit` and
 * `local_path`. Arbitrary depth; `Store` rejects self-parenting and any
 * cycle. The one place it changes behaviour beyond display is visibility:
 * an unscoped read hides a project iff it is archived **or any ancestor
 * is** (`docs/archiving.md`).
 */
parent_id: number | null, 
/**
 * Opt-in (task 1550): this project owns the notebook for every folder
 * under its `local_path` (or a previous path), nested to any depth, git
 * repo or not — the nearest such ancestor wins over the root-commit
 * resolution (`docs/project-memory.md`). Default false.
 */
shared_notebook: boolean, 
/**
 * Folders this project's `local_path` used to be (task 1262), oldest
 * first. Derived on every read from the `project_paths` table, never a
 * column on `projects`: it is a set, and a project may have moved any
 * number of times.
 *
 * It exists because `cc_sessions.cwd` is transcript data matched against
 * `local_path` by exact string equality — move the folder and every
 * older session stops counting toward the project's CC dashboard. The
 * dashboard matches the current path *and* these, so the history
 * survives the move (and survives `mesa cc reset`, which re-ingests the
 * old cwd from the transcripts). Never contains the current
 * `local_path`: `Store::update_project` moves the outgoing value in and
 * takes the incoming one out.
 */
previous_paths: Array<string>, };
