// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * [`ServeNumberSetting`]'s twin for the `allow-host` list.
 */
export type ServeHostsSetting = { value: Array<string> | null, default: Array<string>, effective: Array<string>, 
/**
 * The hosts the command line named, or `null` when it named none.
 */
flag: Array<string> | null, };
