// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * [`ServeNumberSetting`]'s twin for an on/off setting.
 */
export type ServeBoolSetting = { value: boolean | null, default: boolean, effective: boolean, flag: boolean | null, };
