// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One `serve` setting that is a number (the port), as the Settings page sees
 * it (mesa task 1621): what the config says, the built-in default, what this
 * run is using and the command-line flag pinning it, if any.
 */
export type ServeNumberSetting = { 
/**
 * The configured value, or `null` when the config says nothing.
 */
value: number | null, 
/**
 * The built-in default behind a `null` value.
 */
default: number, 
/**
 * The value this process is running with (port) or would use now.
 */
effective: number, 
/**
 * The value the command line pinned, or `null`; set means the config
 * value is ignored this run.
 */
flag: number | null, };
