// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One text-to-speech model's advertised capabilities (`GET /v1/models`,
 * mesa task 1455, `docs/config.md`): whether it clones a reference
 * recording, whether that clone needs a transcript alongside it, whether it
 * can design a voice from a description (the daemon's `x_instruct`), and
 * whether it is naru-audio's own default model — the one a blank `model`
 * setting actually speaks in, which is what a blank drafted model resolves
 * to when the editor needs to know a specific model's capabilities.
 */
export type SpeechModelCaps = { model: string, default: boolean, clone: boolean, clone_requires_transcript: boolean, design: boolean, };
