// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An append-only record of a task's status change. `from_status` is null for
 * the row written when the task is created.
 */
export type TaskEvent = { id: number, task_id: number, 
/**
 * Raw status text, not `Status`: old rows hold retired statuses (`refine`)
 * that no longer parse, and an event must still list them as written.
 */
from_status: string | null, to_status: string, 
/**
 * When the change happened (SQLite `datetime` text, UTC).
 */
at: string, };
