// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One append-only note on a task (naru task 1724). A sibling record, not a
 * `Task` field (the receipt precedent): the task's JSON, `compact()` and
 * `--quiet` key parity stay untouched. There is no update or delete — a
 * note is context added, never a rewrite of what was there.
 */
export type TaskNote = { id: number, task_id: number, 
/**
 * Non-empty, at most `Store::TASK_NOTE_MAX` bytes.
 */
body: string, 
/**
 * The Claude Code session that wrote it, when known (the CLI reads
 * `CLAUDE_CODE_SESSION_ID`); `null` from the web UI.
 */
session: string | null, 
/**
 * SQLite `datetime` text, UTC.
 */
created_at: string, };
