// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AudioState } from "./AudioState";

/**
 * What `GET /api/live/transcribe` answers (mesa task 1388): whether the
 * server's speech-to-text engine is ready, and if not, the sentence the
 * page shows the person. `available` is `state == "ready"` — whether the
 * POST can decode — kept for clients that only read it.
 */
export type TranscribeStatus = { available: boolean, state: AudioState, 
/**
 * `audio.engine`: `"legacy"` or `"naru-audio"`.
 */
engine: string, 
/**
 * The daemon's URL on `naru-audio`; `null` on `legacy`.
 */
url: string | null, 
/**
 * `null` when ready.
 */
message: string | null, 
/**
 * When the (cached) answer was taken, RFC 3339 UTC.
 */
checked_at: string, };
