// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VoiceEnrollSample } from "./VoiceEnrollSample";

/**
 * Speaker-enrollment status (naru task 1744, `docs/voice-enrollment.md`,
 * `GET /api/config/voice-enrollment`): the recording the browser saved and
 * the enrollment the Naru Mac app built from it.
 */
export type VoiceEnrollment = { sample: VoiceEnrollSample | null, 
/**
 * When `ambient-enrollment.json` was last written, if it exists.
 */
enrolled_at: string | null, 
/**
 * The enrollment exists and is not older than the sample.
 */
current: boolean, };
