// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A cloned voice as one file (mesa task 1430,
 * `GET /api/config/speech/voices/{name}`, `docs/config.md`): what Settings'
 * **export** downloads and **import** reads back, on this machine or
 * another. `format` is always `"naru-voice"` and `version` `1`; a reader
 * refuses anything else rather than guess at it.
 */
export type VoiceExport = { 
/**
 * Always `"naru-voice"`.
 */
format: string, 
/**
 * The format's version, `1`.
 */
version: number, 
/**
 * The voice's name where it was exported — the default name on import.
 */
name: string, 
/**
 * Exactly what the clip says: the voice's transcript.
 */
text: string, 
/**
 * The clip (naru-audio's `ref.wav`), byte for byte, as standard base64.
 */
wav_base64: string, };
