// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The saved speaker-enrollment recording (naru task 1744).
 */
export type VoiceEnrollSample = { 
/**
 * File size in bytes.
 */
bytes: number, 
/**
 * Length in seconds.
 */
seconds: number, 
/**
 * When it was saved (UTC, ISO 8601).
 */
recorded_at: string, };
