// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A cloned voice as one file (mesa task 1430,
 * `GET /api/config/speech/voices/{name}`, `docs/config.md`): what Settings'
 * **export** downloads and **import** reads back, on this machine or
 * another. `format` is always `"naru-voice"` and `version` `1`; a reader
 * refuses anything else rather than guess at it.
 */
export type VoiceExport = { 
/**
 * Always `"naru-voice"`.
 */
format: string, 
/**
 * The format's version, `1`.
 */
version: number, 
/**
 * The voice's name where it was exported — the default name on import.
 */
name: string, 
/**
 * Exactly what the clip says: the voice's transcript. May be empty for
 * a voice cloned onto a model that never needed one.
 */
text: string, 
/**
 * The clip (naru-audio's `ref.wav`), byte for byte, as standard base64.
 */
wav_base64: string, 
/**
 * The model the voice was cloned for (mesa task 1455), `null` for a
 * file exported before this field existed — a version-1-compatible
 * addition, `docs/config.md` says a reader ignores keys it doesn't
 * know, so an older reader is unaffected. Importing such a file to a
 * different model is refused; one with no `model` is always allowed,
 * landing on whichever model the import names.
 */
model: string | null, };
