// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the Settings page's **design a voice** panel needs (mesa task 1426,
 * `GET /api/config/speech/design`).
 */
export type VoiceDesign = { 
/**
 * Whether naru-audio has `model` (below) pulled. Always `false` on the
 * legacy engine, and when Naru could not ask the daemon.
 */
available: boolean, 
/**
 * The voice-design model this reflects (mesa task 1455) — the one the
 * editor's `?model=` named, echoed back for the `naru-audio pull` hint;
 * blank when none was named.
 */
model: string, 
/**
 * The short line an audition reads.
 */
sample: string, 
/**
 * The reference script a kept design reads — the saved clone's
 * transcript.
 */
reference: string, };
