// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a [`WorkflowNode`] does. Exactly six — the config of each is
 * validated by `core::workflow::validate_config`, so a seventh kind is
 * a change to the engine, the validator and the editor together.
 */
export type WorkflowNodeKind = "trigger" | "prompt" | "cli" | "script" | "branch" | "output";
