// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkflowBranch } from "./WorkflowBranch";

/**
 * A directed edge between two nodes of one workflow. A workflow is a DAG:
 * `Store` refuses a self-edge or a cycle (`cycle`).
 */
export type WorkflowEdge = { id: number, workflow_id: number, from_node: number, to_node: number, 
/**
 * `true`/`false` on an edge leaving a branch node (required there),
 * null on every other edge.
 */
branch: WorkflowBranch | null, };
