// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Workflow } from "./Workflow";
import type { WorkflowEdge } from "./WorkflowEdge";
import type { WorkflowNode } from "./WorkflowNode";

/**
 * A workflow with all its nodes and edges: `show`'s payload and `delete`'s
 * echo, so a client renders (or recovers) a whole graph from one object.
 */
export type WorkflowView = { workflow: Workflow, nodes: Array<WorkflowNode>, edges: Array<WorkflowEdge>, };
