// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One line an `output` node with `target: log` appended to a named log.
 * Append-only; `workflow_id`/`run_id` are `ON DELETE SET NULL`, so the line
 * outlives the run and the workflow that wrote it.
 */
export type WorkflowLogEntry = { id: number, log: string, text: string, workflow_id: number | null, run_id: number | null, created_at: string, };
