// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How one node ended in a run. `skipped` is a node no active edge
 * reached, or one a failure upstream stopped from running.
 */
export type WorkflowStepStatus = "ok" | "skipped" | "failed";
