// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How one node ended in a run. `skipped` is a node no active edge
 * reached, or one a failure upstream stopped from running. `running` is
 * a node in flight: it appears only on a run that is itself still
 * `running`, and is replaced by the node's final step.
 */
export type WorkflowStepStatus = "running" | "ok" | "skipped" | "failed";
