// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A directed edge between two nodes of one workflow. A workflow is a DAG:
 * `Store` refuses a self-edge or a cycle (`cycle`).
 */
export type WorkflowEdge = { id: number, workflow_id: number, from_node: number, to_node: number, 
/**
 * The label an edge leaves its source on: `true`/`false` on an edge
 * leaving a branch node, one of the node's options or `fallback` on an
 * edge leaving a decide node (required on both), null on every other
 * edge.
 */
branch: string | null, };
