// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkflowRunStatus } from "./WorkflowRunStatus";
import type { WorkflowStep } from "./WorkflowStep";
import type { WorkflowTrigger } from "./WorkflowTrigger";

/**
 * One execution of a workflow. The row is written `running` first and
 * finished once; a failed run is still a recorded run.
 */
export type WorkflowRun = { id: number, workflow_id: number, trigger: WorkflowTrigger, 
/**
 * The text the trigger node handed on (may be empty).
 */
input: string, status: WorkflowRunStatus, steps: Array<WorkflowStep>, error: string | null, started_at: string, finished_at: string | null, };
