// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkflowNodeKind } from "./WorkflowNodeKind";
import type { WorkflowStepStatus } from "./WorkflowStepStatus";

/**
 * One node's outcome inside a [`WorkflowRun`].
 */
export type WorkflowStep = { node_id: number, title: string, kind: WorkflowNodeKind, status: WorkflowStepStatus, 
/**
 * What the node produced, capped at 64 KiB.
 */
output: string, error: string | null, duration_ms: number, };
