// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which verdict of a `branch` node an edge leaves on. Only an edge whose
 * `from_node` is a branch carries one, and there it is required.
 */
export type WorkflowBranch = "true" | "false";
