// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkflowTrigger } from "./WorkflowTrigger";

/**
 * A named graph, optionally bound to a project. The name is unique across
 * **all** workflows (case-insensitively) so the CLI and the voice agent can
 * run one by name.
 *
 * `trigger` and `trigger_phrase` are **derived on every read** from the
 * workflow's trigger node, never stored here: they are what lets
 * `workflow list` say which workflows a spoken phrase could mean without
 * loading every graph.
 */
export type Workflow = { id: number, 
/**
 * The project the workflow belongs to, or null for a global one. Its
 * `local_path` is a `cli` node's working directory. The FK is
 * `ON DELETE CASCADE`: a workflow about a project goes with it.
 */
project_id: number | null, name: string, description: string | null, 
/**
 * The trigger node's `mode`, or null when the workflow has no trigger.
 */
trigger: WorkflowTrigger | null, 
/**
 * The trigger node's `phrase` (voice), or null.
 */
trigger_phrase: string | null, created_at: string, updated_at: string, };
