// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkflowNodeKind } from "./WorkflowNodeKind";

/**
 * One step of a graph. `config` is JSON whose shape depends on `kind`
 * (documented in `docs/workflows.md`), so it is typed in TypeScript as a
 * plain object: the editor narrows it by `kind`, and `Store` has already
 * refused any key or value the kind does not allow.
 */
export type WorkflowNode = { id: number, workflow_id: number, kind: WorkflowNodeKind, title: string, config: Record<string, unknown>, x: number, y: number, created_at: string, updated_at: string, };
